# Generated by Django 3.2.9 on 2021-11-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_name', models.CharField(blank=True, max_length=50, null=True)),
                ('clothing_type', models.IntegerField(blank=True, choices=[(1, 'shirt'), (2, 'dress'), (3, 'pants'), (4, 'blouse'), (5, 'skirt')], null=True)),
                ('clothing_color', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('discounted_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
